
import { Geist, Geist_Mono } from "next/font/google";
import { ConfigProvider } from "antd";
import React from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";
import Header from '../components/Header';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              cssVar: true,
              token: {
                colorPrimary: '#6d7ec2',
              },
            }}
          >
            {/* 2. Place Header here so it appears on all pages */}
            <Header /> 
            
            {/* 3. The main content of each page renders here */}
            <main>{children}</main> 
            
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}

