
import { Geist, Geist_Mono } from "next/font/google";
import { ConfigProvider} from "antd"
import React from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry> {/* Wrap registry around the theme provider */}
          <ConfigProvider
            theme={{
              cssVar: true,
              token: {
                colorPrimary: '#6d7ec2',
                colorSuccess: '#04AA6D',
              },
            }}
          >
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  )
}
